### ISSUE TITLE
Did this pass the assignment?

### ISSUE THREAD

**Issue by mapleroyal** [nick-noob/d280-interactive-world-map#1]
Hey, looks good!

Just checking if this passed the assignment, because one of the instructions suggests it needs a field for the user type the name of the country, but I've seen it both ways in other classmates' repos. The video WGU shows in the tips has an input field for search, but the instructor doesn't mention it at all in the video. Here's the instruction that concerns me:

**one method that accepts a country name as an input parameter that returns additional information gathered from the API for the selected country**

**Comment by nick-noob** [comment]
Hello! 

Yeah it sure did. Passed on the first attempt. 

I believe using the country code as the input parameter when clicking on a specific country is sufficient to meet the instruction you are inquiring about.

**Comment by mapleroyal** [comment]
Thanks! Got mine all working, but I've got another quick question. The assignment says to turn this in:

G.  Provide a compressed file of your website, including each of the following files:
●   HTML
●   TS
●   SVG
●   JSON configuration files

Surely what it means is, zip up the complete angular project, right? They aren't actually asking for one single html file, one single ts file, an svg, and some json files, right?

Better to ask than wait 6 days while they decide to reject it.

**Comment by nick-noob** [comment]
Nice work! And yes, you are correct. Zip up the project folder and submit that. That's what I did and here's what the .ZIP contained:

![d280-zip-package](https://github.com/nick-noob/d280-interactive-world-map/assets/106461792/dd574a64-6ba4-4662-81e3-e1206fbb5ee7)
